version: '3.8'

services:
  # MySQL Database
  mysql:
    image: mysql:8.0
    container_name: quiz-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-rootpassword}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-quiz_app}
      MYSQL_USER: ${MYSQL_USER:-quizuser}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-quizpassword}
    ports:
      - "${MYSQL_PORT:-3306}:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD:-rootpassword}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - quiz-network

  # Backend Express API
  backend:
    build: ./backend
    container_name: quiz-backend
    restart: unless-stopped
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      - NODE_ENV=production
      - PORT=5000
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_NAME=${MYSQL_DATABASE:-quiz_app}
      - DB_USER=${MYSQL_USER:-quizuser}
      - DB_PASSWORD=${MYSQL_PASSWORD:-quizpassword}
    ports:
      - "${BACKEND_PORT:-5000}:5000"
    networks:
      - quiz-network

  # Frontend React App
  frontend:
    build: ./frontend
    container_name: quiz-frontend
    restart: unless-stopped
    depends_on:
      - backend
    ports:
      - "${FRONTEND_PORT:-80}:80"
    environment:
      - REACT_APP_API_URL=http://localhost:${BACKEND_PORT:-5000}/api
    networks:
      - quiz-network

networks:
  quiz-network:
    driver: bridge

volumes:
  mysql-data:
    driver: local
